services:
  source-db:
    image: container-registry.oracle.com/database/free:23.4.0.0
    container_name: source-db
    environment:
      - ORACLE_PWD=source
    volumes:
      - ./startupScriptSource:/opt/oracle/scripts/startup
    ports:
      - "1521:1521"
  target-db:
    image: container-registry.oracle.com/database/free:23.4.0.0
    container_name: target-db
    environment:
      - ORACLE_PWD=target
    volumes:
      - ./startupScriptTarget:/opt/oracle/scripts/startup
    ports:
      - "1621:1521"
  ogg:
    image: container-registry.oracle.com/goldengate/goldengate-free:latest
    container_name: ogg
    ports:
      - "8080:80"
