- name: Fetch docker repo
  ansible.builtin.command: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo

- name: Install docker
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: latest
  ignore_errors: "{{ ansible_check_mode }}"

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_env.SUDO_USER  }}"
    groups: docker
    append: yes
  ignore_errors: "{{ ansible_check_mode }}"
  notify:
    - Restart docker
