version: '3.9'

services:
  prometheus-server:
    image: prom/prometheus
    container_name: prometheus-server
    restart: unless-stopped
    volumes:
      - ./config/prometheus.yml:/etc/prometheus.yml
      - ./prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - ./node-exporter-volume:/volume_dir
    expose:
      - 9100