---
- name: Restart docker
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: "{{ item }}"
    enabled: true
  loop:
    - docker.socket
    - docker.service
  ignore_errors: "{{ ansible_check_mode }}"
