global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - rules.yml

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
      - targets: ['alertmanager-server:9093']

scrape_configs:
  - job_name: file
    file_sd_configs:
     - files:
       - '*.json'