alter session set container = freepdb1;
CREATE USER project_manager IDENTIFIED BY source##123;
GRANT CONNECT, RESOURCE TO project_manager;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE, CREATE TRIGGER, CREATE SYNONYM TO project_manager;
ALTER USER project_manager QUOTA UNLIMITED ON USERS;